repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^ritest/legacy-slow/|^benchmarks/Stata/
      - id: ruff-format
        exclude: ^ritest/legacy-slow/|^benchmarks/Stata/
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        exclude: ^ritest/legacy-slow/|^benchmarks/Stata/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^ritest/legacy-slow/|^benchmarks/Stata/
      - id: trailing-whitespace
        exclude: ^ritest/legacy-slow/|^benchmarks/Stata/
