repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        files: \.pyi?$
        exclude: ^documentation/benchmarks/.*/output/|\.do$
      - id: ruff-format
        files: \.pyi?$
        exclude: ^documentation/benchmarks/.*/output/|\.do$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^documentation/benchmarks/.*/output/|\.do$
      - id: trailing-whitespace
        exclude: ^documentation/benchmarks/.*/output/|\.do$
